name: assembly

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [4]
      type: low_dim
  action:
    shape: [4]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.metaworld_dataset.MetaworldDataset
  zarr_path: data/metaworld_assembly_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
